_G['Class'] = require('Base.DataType.Class')()
_G['Event'] = require('Base.DataType.Event')()
_G['Interface'] = require('Base.DataType.Interface')()
_G['Property'] = require('Base.DataType.Property')()
_G['Enum'] = require('Base.DataType.Enum')()